### ISSUE TITLE
Google auth

### ISSUE THREAD

**Issue by darksuei** [darksuei/cloudwave#46]

**Comment by corners2wall** [comment]
Cood you me more advice for this issues? I will try develop this

**Comment by Suei43** [comment]
Hi, would be nice if we could add an option for users to signup/signin with their google accounts.

**Comment by Suei43** [comment]
@corners2wall Shall i assign you this?

**Comment by corners2wall** [comment]
@Suei43  Yeap I will try

**Comment by Suei43** [comment]
You can reach out to me >> sueii on discord if you need more information.
